mozilla-l10n/zerda-android-l10n

- locales/id/app.po
- locales/templates/app.pot
https://conjuror.github.io/Zerda-Screenshots/index.html
> Strings for rocket 1.0

- locales/id/app.po
- locales/templates/app.pot
This is not new strings awaiting to be localized, but some contents we're sharing with focus and we're leveraging the existing localization. This pull request is here to sync what we have reused and probably have them reviewed.
> Export 2017 11 06

- locales/id/app.po
- locales/templates/app.pot
This is an export of the strings that will be used in the next release.
In earlier discussions, we planned to release on Jan 16th with these strings. However the development of the feature that uses these strings is preempted by a hot fix. As a consequence, this feature is still under development and the release date is not yet settled. I'll invite our EPM Wesley to comment on the final decision / deadline of these.
> Export 2018 01 10

- locales/id/app.po
- locales/templates/app.pot
Summary:
1. Change On-boarding message ads and trackers -> trackind ads
2. New strings for notifications survey_notification_title / survey_notification_description ~/ survey_notification_title_pre_v24~
~For # 2 The best practice to handle a set of strings which should behave differently on different Android versions is to separate them by files, however I feel like doing that with Pontoon would create unnecessary complexity so I go with the safer way.~
> Export 2018 01 15

- locales/id/app.po
- locales/templates/app.pot
- locales/zh-CN/app.po
Release: 1.0.5
Targeted deadline: Mar 14th
> Export 2018 03 13 (Rocket 1.0.5) 

- locales/id/app.po
- locales/templates/app.pot
- locales/zh-CN/app.po
These are the new strings for Rocket 2.0 (updated)
> Export 2018 03 23 (Rocket 2.0)

- locales/id/app.po
- locales/templates/app.pot
- locales/zh-CN/app.po
One new string: "Open image in new tab"
> Export 2018 04 09 (Rocket 2.0 part 2) 

- locales/id/app.po
- locales/templates/app.pot
- locales/zh-CN/app.po
l10n for Rocket 2.1 See [here](https://github.com/mozilla-tw/Rocket/wiki) for the schedule of the release.
Related issues on rocket:
https://github.com/mozilla-tw/Rocket/issues/1412 [2 new strings](https://github.com/mozilla-tw/Rocket/commit/28964c0143600d5c8adc8560362668a1073affb0)
https://github.com/mozilla-tw/Rocket/issues/346 [4 new strings](https://github.com/mozilla-tw/Rocket/commit/0958266aa241cf0e57ae0a1f16d74efd48672b7a)
> Export 2018 04 30

- locales/id/app.po
- locales/templates/app.pot
- locales/zh-CN/app.po
l10n for Rocket 2.3 See [here](https://github.com/mozilla-tw/Rocket/wiki) for the schedule of the release.
[mozilla-tw/Rocket#1104](https://github.com/mozilla-tw/Rocket/issues/1104) 11 [new strings](https://github.com/mozilla-tw/Rocket/pull/2075/files)
[mozilla-tw/Rocket#1327](https://github.com/mozilla-tw/Rocket/issues/1327) 2 [new strings](https://github.com/mozilla-tw/Rocket/pull/2069/files#diff-01dafb3fd0217441330103cfc8300094)
> Export 2018 06 22

- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/pa-IN/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/zh-CN/app.po
This is an update due to some build change in Rocket source code. We've also made the change in each locale so there are no new items but just items that would need some review.
> Export 2018 07 18

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/zh-CN/app.po
l10n for Rocket Canlaon
[Show "... wants to access your location" message too many times when searching](https://github.com/mozilla-tw/Rocket/issues/1654) - [1](https://github.com/mozilla-tw/Rocket/pull/2518/files#diff-01dafb3fd0217441330103cfc8300094) new string.
> Export 2018 08 30 (Canlaon) (Revised)

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/zh-CN/app.po
l10n for Rocket Dena
[Experiment: VPN Offering](https://github.com/mozilla-tw/Rocket/issues/1820) -
[Experiment: Wifi Finder Offering (Landing Page Test)](https://github.com/mozilla-tw/Rocket/issues/1821) - [5](https://github.com/mozilla-tw/Rocket/pull/2585/files) new string.
[Find in page](https://github.com/mozilla-tw/Rocket/issues/1891) - [1](https://github.com/mozilla-tw/Rocket/pull/2538/files#diff-01dafb3fd0217441330103cfc8300094) + [6](https://github.com/mozilla-tw/Rocket/pull/2544/files#diff-01dafb3fd0217441330103cfc8300094) new strings.
> Export 2018 09 13

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/zh-CN/app.po
l10n for Rocket Everest
[new Private Browsing tab from menu](https://github.com/mozilla-tw/Rocket/issues/2533) - [1](https://github.com/mozilla-tw/Rocket/pull/2686) new string.
[Night mode](https://github.com/mozilla-tw/Rocket/issues/1910) - [2](https://github.com/mozilla-tw/Rocket/pull/2683/files) new strings.
> Export 2018 09 27 (Everest)

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/zh-CN/app.po
l10n for Rocket Fuji
[Brand Change Transition Experience](https://github.com/mozilla-tw/Rocket/issues/2299) - [4 new strings and 3 string changes.](https://github.com/mozilla-tw/Rocket/commit/137edc3d39f8707ac0f85e17ef657c5cf695ba65)
[Handling Permissions Denials](https://github.com/mozilla-tw/Rocket/issues/2692) - [2 new strings.](https://github.com/mozilla-tw/Rocket/commit/1c290085fea47f807d86430ea18f8a22c4f6cf8a)
> Export 2018 10 11 (Fuji)

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/zh-CN/app.po
l10n for Rocket Fuji (2)
There's something we'd like to add in sprint Fuji and we will re-organize schedule accordingly. Wesley will share more later
[Love Firefox Rocket options](https://github.com/mozilla-tw/Rocket/issues/2693) - [3 string changes.](https://github.com/mozilla-tw/Rocket/pull/2763/files)
> Export 2018 10 16 (Fuji 2)

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/zh-CN/app.po
l10n for Rocket Hallasan
Adding [one string](https://github.com/mozilla-tw/Rocket/commit/2a0bbff49033d40313bd59e9c001e4e4be47102e) for [VPN Recommender](https://github.com/mozilla-tw/Rocket/issues/2770)
> Export 2018 11 02 (Hallasan 2)

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/zh-CN/app.po
l10n for Rocket Lhotse
See here for the [schedule](https://github.com/mozilla-tw/Rocket/wiki/Release-Schedule) of the release.
Related issues on Rocket: [Downland Manager Enhancement](https://github.com/mozilla-tw/Rocket/issues/2002)
> Export 2019 01 03 (Lhotse)

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
l10n for Rocket Qbatta 
See here for the [schedule](https://github.com/mozilla-tw/FirefoxLite/wiki/Release-Schedule) of the release.
Adding [4 strings](https://github.com/mozilla-tw/FirefoxLite/pull/3361/files) for Pin site & News title strings
> Export 2019 03 22

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
This pull request fixes the reviewed comment in #39
> Export 2019 04 07

- locales/ace/app.po
- locales/anp/app.po
- locales/bn-IN/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
> Export 2019 04 20

- locales/ace/app.po
- locales/anp/app.po
- locales/bn/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
> Export 2019 10 04

- locales/ace/app.po
- locales/anp/app.po
- locales/bn/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
1. l10n PR for sprint S4-4 feature (e.g. confirm exit FxLite feature)
> Export 2020 05 19

- locales/ace/app.po
- locales/anp/app.po
- locales/bn/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
1. Firefox Lite l10n for Sprint 4-7 milestone (e.g. default browser, customized home)
2. Fix typo and rewording based on review suggestions from https://github.com/mozilla-l10n/zerda-android-l10n/pull/67
> Export 2020 05 28

- locales/ace/app.po
- locales/anp/app.po
- locales/bn/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
1. Strings for Firefox Lite [Sprint 4-8 milestone ](https://github.com/mozilla-tw/FirefoxLite/issues?q=is%3Aclosed+milestone%3A%22S4-8+%28June-8~June-19%29%22)
2. Strings for features are menu items, add top sites toast and snackbar, refine the title of "set default browser"
> Export 2020 06 10

- locales/ace/app.po
- locales/anp/app.po
- locales/bn/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
1. l10n PR for Firefox Lite [milestone 4-9 ](https://github.com/mozilla-tw/FirefoxLite/milestone/70) (e.g. Onboarding UI and transition , Theme settings, Top site category update )
> Export 2020 06 23

- locales/ace/app.po
- locales/anp/app.po
- locales/bn/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
Firefox Lite team just found missing strings for awesome bar in Sprint 4-8.
Please take a look, thanks Delphine !
1.  l10 PR for Sprint 4-8 awesome bar feature.
> Export 2020 06 29

- locales/ace/app.po
- locales/anp/app.po
- locales/bn/app.po
- locales/gor/app.po
- locales/gu-IN/app.po
- locales/hi-IN/app.po
- locales/id/app.po
- locales/jv/app.po
- locales/kn/app.po
- locales/mai/app.po
- locales/ml/app.po
- locales/mr/app.po
- locales/pa-IN/app.po
- locales/ru/app.po
- locales/su/app.po
- locales/ta/app.po
- locales/te/app.po
- locales/templates/app.pot
- locales/th/app.po
- locales/tl/app.po
- locales/vi/app.po
- locales/zh-CN/app.po
- locales/zh-TW/app.po
This time we have final changes for v2.5 Release about,
1. Remove unused strings for old onboarding.
2. Reframe awesomebar_open_link_clipboard strings 
3. Add survey feature related strings
> Export 2020 07 16
